name: Feature request
description: Suggest something prs should do
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: What are you trying to do, and what would you want prs to do about it?
    validations:
      required: true
