name: Feature request
description: An idea to make prs better
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: What you're trying to do and how you'd like prs to help.
    validations:
      required: true
